### ISSUE TITLE
Hackage upload?

### ISSUE THREAD

**Issue by pschuprikov** [markus1189/hoggl#12]
Hi, could you consider uploading a new hackage version? I saw #5, so if any help is needed just let me know.

**Comment by markus1189** [comment]
Hey @pschuprikov will have a look in the next days :)

**Comment by markus1189** [comment]
@greenrd I'm not a maintainer for `hoggl` and so can't upload.  Please add me `markus1189`

**Comment by cdepillabout** [comment]
@markus1189 There is also a procedure for taking over a package on Hackage in cases like these:

https://wiki.haskell.org/Taking_over_a_package

I think the "reasonable time to respond" has passed for @greenrd, so I'd go ahead and contact the Hackage maintainers.

The comments on #5 should be more than enough to have you added as a maintainer for the package.

**Comment by greenrd** [comment]
@markus1189 Sorry for the delay, just added you.

**Comment by markus1189** [comment]
Published https://hackage.haskell.org/package/hoggl-0.2.0.1
