### ISSUE TITLE
Some daily totals wrong in output of week command

### ISSUE THREAD

**Issue by greenrd** [markus1189/hoggl#3]
I get:

```
$ hoggl --token xxxxxxxxxxxxxxxxxxxxxxxxxx week
2016-08-02: 2h 37m
2016-08-03: 6h 30m
2016-08-04: 7h 26m
2016-08-05: 6h 33m
2016-08-06: 1h 30m
Total: 35h 0m
```

The total for the week is correct, but the total for Tuesday is wrong, and Monday doesn't even show up.

**Comment by greenrd** [comment]
I did some debugging and it turns out this happens because you haven't implemented pagination support for detailed report requests.

**Comment by markus1189** [comment]
That's very much possible ;)  Currently I use it for a very narrow use case.  I don't know how much time I'll be able to spend on features, any interest to fix this?

**Comment by greenrd** [comment]
Right now I am planning to write my own version of a Toggl library for my different use case. But if I change my mind, I will let you know.

**Comment by markus1189** [comment]
Let me know once you have something running, I might be interested ;)
