### ISSUE TITLE
Hackage upload?

### ISSUE THREAD

**Issue by greenrd** [markus1189/hoggl#5]
I would be happy to upload both versions for you. It would make depending on Hoggl more convenient and would allow cabal to automatically pick the best version based on other dependency constraints.

**Comment by markus1189** [comment]
What do you mean by both versions? I'll have a look at uploading hoggl to hackage in the next days myself, I just never bothered because there was (rightly, as there are no docs ;) ) no interest.  I am happy to change this though

**Comment by greenrd** [comment]
I mean 0.1.0.0 and 0.2.0.0.

**Comment by greenrd** [comment]
_reminder_

**Comment by greenrd** [comment]
I've done it. If you create an account on hackage and tell me your username, I will add you as a maintainer for hoggl on hackage.

**Comment by markus1189** [comment]
Fair enough, somehow I successfully procrastinated this the whole time :P  Thanks for taking the initiative, I am already the maintainer on hackage, but if you still need it: `markus1189` is also my hackage name.
